[project]
name = "monami"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.128.0",
    "neomodel>=6.0.1",
    "pydantic>=2.12.5",
    "requests>=2.31.0",
    "uvicorn>=0.40.0",
]
